spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    show-sql: true
    hibernate:
      use_sql_comments: true
      format_sql: true